name: Python package

on:
  push:
    branches:
    - Chetabahana

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python: [ '3.8' ]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Test Dependencies
      run: |
        bash .github/workflows/builders/__init__
      env:
        TAG_NAME: ubuntu
        BRANCH_NAME: Chetabahana
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        GCP_ACCOUNT: ${{ secrets.GCP_ACCOUNT }}
        TRANSIFEXRC: ${{ secrets.TRANSIFEXRC }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
